export { DEFAULT_BACKDROP_CONFIG, resolveBackdropConfig } from "./config";
export { BackdropEngine } from "./core/BackdropEngine";
export { SceneCompositor } from "./core/SceneCompositor";
export { EmberScene } from "./scenes/EmberScene";
export { NeuralScene } from "./scenes/NeuralScene";
export { RainScene } from "./scenes/RainScene";
export { StarfieldScene } from "./scenes/StarfieldScene";
export { CollapseTransition } from "./transitions/CollapseTransition";
export { PortalTransition } from "./transitions/PortalTransition";
export { WarpTransition } from "./transitions/WarpTransition";
export { transitionKey } from "./domain/types";
export { mixRgb, pulse, rgba } from "./utils/colour";
export { clamp01, easeInOut } from "./utils/easing";
export type { BackdropConfig, BackdropConfigOverrides } from "./config";
export type { BackdropOptions } from "./core/BackdropEngine";
export type { EmberSceneOptions } from "./scenes/EmberScene";
export type { NeuralSceneOptions } from "./scenes/NeuralScene";
export type { RainSceneOptions } from "./scenes/RainScene";
export type { StarfieldSceneOptions } from "./scenes/StarfieldScene";
export type { CollapseTransitionOptions } from "./transitions/CollapseTransition";
export type { PortalTransitionOptions } from "./transitions/PortalTransition";
export type { WarpTransitionOptions } from "./transitions/WarpTransition";
export type { Rgb } from "./utils/colour";
export type { BackdropFrame, Scene, SceneFactory, SceneSize, SceneTransition, TransitionFactory } from "./domain/types";
