import { AchievementSpec, CounterKind } from "../domain/progress";

const achievement = (id: string, counter: string, target: number, reward: string | null = null): AchievementSpec => ({ id, counter, target, reward });

// How each lifetime count grows: added to for each time something happens, or the best ever reached. A count of
// distinct things (the worlds landed on) is kept by its prefix, one entry each.
export const COUNTERS: Readonly<Record<string, CounterKind>> = {
  runs: "count",
  landings: "count",
  landedWorlds: "best",
  kills: "count",
  bosses: "count",
  bestStreak: "best",
  railMulti: "best",
  empStunned: "count",
  mineKills: "count",
  rescues: "count",
  deflections: "count",
  universes: "best",
  gates: "count",
  wormholes: "count",
  heard: "count",
  hosted: "count",
  salvaged: "count",
  coins: "count",
  crafted: "count",
  shipLevel: "best",
  enhanceBest: "best",
  pilotLevel: "best",
  starTotal: "best",
  perfectUniverses: "count",
  dailyRuns: "count",
  docked: "count",
  distress: "count",
  chests: "count",
  boostsUsed: "count",
  xFlares: "count",
  stormsTurned: "count",
  sunBrush: "count",
};

// Fifty achievements, from the first flight to a legend, a paint or an engine trail for many of them.
export const ACHIEVEMENTS: readonly AchievementSpec[] = [
  achievement("firstFlight", "runs", 1),
  achievement("firstLanding", "landings", 1),
  achievement("moonWalker", "landed:moon", 1),
  achievement("redPlanet", "landed:mars", 1),
  achievement("hellLanding", "landed:venus", 1),
  achievement("titanDive", "landed:titan", 1),
  achievement("everyRocky", "landedWorlds", 8, "explorer"),
  achievement("sunBrush", "sunBrush", 1),
  achievement("flareSurvivor", "xFlares", 1),
  achievement("stormTurned", "stormsTurned", 1),
  achievement("beyondTheEdge", "universes", 1, "horizon"),
  achievement("firstBlood", "kills", 1),
  achievement("hunter", "kills", 50),
  achievement("ace", "kills", 250, "ace"),
  achievement("exterminator", "kills", 1000, "crimsonTrail"),
  achievement("bossSlayer", "bosses", 1),
  achievement("bossHunter", "bosses", 10, "obsidian"),
  achievement("streak10", "bestStreak", 10),
  achievement("streak30", "bestStreak", 30, "rainbow"),
  achievement("railMulti", "railMulti", 3),
  achievement("empStun", "empStunned", 10),
  achievement("mineLayer", "mineKills", 10),
  achievement("saviour", "rescues", 5),
  achievement("deflector", "deflections", 1),
  achievement("universes5", "universes", 5, "synthwave"),
  achievement("universes10", "universes", 10, "voidTrail"),
  achievement("universes20", "universes", 20, "aurora"),
  achievement("mazeRunner", "gates", 10),
  achievement("wormholer", "wormholes", 1),
  achievement("darkForest", "heard", 1),
  achievement("welcomed", "hosted", 3),
  achievement("salvager", "salvaged", 25),
  achievement("rich", "coins", 5000),
  achievement("crafter", "crafted", 10),
  achievement("shipwright", "shipLevel", 10),
  achievement("titanForm", "shipLevel", 25, "titanGold"),
  achievement("moonForge", "enhanceBest", 10),
  achievement("starForge", "enhanceBest", 20, "starlight"),
  achievement("galaxyForge", "enhanceBest", 30, "galactic"),
  achievement("level10", "pilotLevel", 10),
  achievement("level50", "pilotLevel", 50),
  achievement("level100", "pilotLevel", 100, "plasma"),
  achievement("level300", "pilotLevel", 300, "legend"),
  achievement("stars30", "starTotal", 30),
  achievement("perfect", "perfectUniverses", 1),
  achievement("daily7", "dailyRuns", 7),
  achievement("docked", "docked", 1),
  achievement("distress", "distress", 5),
  achievement("chests", "chests", 10),
  achievement("boostsUsed", "boostsUsed", 50),
];
